name: 'Syntax:Lab2'
description: 'Action of Lab2 in Syntax section'
inputs:
  text:
    description: Text that will be uppercased
    required: true
outputs:
  upper_text:
    description: Text in uppercase
    value: ${{ steps.upper_step.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: upper_step
      run: |
        echo "${INPUT_TEXT^^}"
      env:
        INPUT_TEXT: ${{ inputs.text }}
      shell: bash